apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandra-rc
    uniqid: salmon
  name: cassandra-salmon
spec:
  replicas: 1
  selector:
    name: cassandra-pod
    uniqid: salmon
  template:
    metadata:
      labels:
        name: cassandra-pod
        uniqid: salmon
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.io/google_containers/cassandra:v6
          name: cassandra-db
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
      volumes:
        - name: cassandra-data
          gcePersistentDisk:
            pdName: cassandra-disk-salmon
            fsType: ext4
